pipeline {
    agent any
 
    tools {
        maven 'Maven3'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/Akashraj44/WIPRO_PROJECT.git'
                    
            }
        }
 
          stage('Build') {
            steps {
                dir('NewProject_PHP') {
                    bat 'mvn clean'
                }
            }
        }
 
        stage('Compile') {
            steps {
                dir('NewProject_PHP') {
                    bat 'mvn compile'
                }
            }
        }
 
        stage('Test') {
            steps {
                dir('TNewProject_PHP') {
                    bat 'mvn test'
                }
            }
        }
 
        stage('Package') {
            steps {
                dir('NewProject_PHP') {
                    bat 'mvn package'
                }
            }
        }
    }
 
    post {
        success {
            echo 'Build Successful'
        }
 
        failure {
            echo 'Build Failed'
        }
    }
}