pipeline {
    agent any
 
    tools {
        maven 'Maven3'
        jdk 'JDK'
    }
 
    stages {
 
        stage('Checkout') {
            steps {
                git branch: 'master',
                    url: 'https://github.com/Akashraj44/WIPRO_PROJECT.git'
                    
            }
        }
 
          stage('Build') {
            steps {
                dir('NewProject_PHP') {
                    bat 'mvn clean'
                }
            }
        }
 
        stage('Compile') {
            steps {
                dir('NewProject_PHP') {
                    bat 'mvn compile'
                }
            }
        }
 
        stage('Test') {
            steps {
                dir('NewProject_PHP') {
                    bat 'mvn test'
                }
            }
        }
 
        stage('Package') {
            steps {
                dir('NewProject_PHP') {
                    bat 'mvn package'
                }
            }
        }
    }
    stage('Docker Build') {

    steps {
	
          dir('NewProject_PHP'){
        bat 'docker build -t cucumber-framework .'
     }

    }

}

 

stage('Docker Run') {

    steps {
	   
          dir('NewProject_PHP'){
        bat 'docker run --rm cucumber-framework'
     }

    }

}

   post {

        always {
            junit allowEmptyResults: true,
                  testResults: 'CucumberBDD2/target/junitreports/*.xml'

            archiveArtifacts artifacts: 'CucumberBDD2/target/*/.*',
                             fingerprint: true
        }

        success {
            echo 'Build Successful'
        }

        failure {
            echo 'Build Failed'
        }
    }
}